import { PrismaClient } from '@prisma/client';

export async function seedCurrencies(prisma: PrismaClient) {
  const currencies = [
    { code: 'AED', name: 'UAE Dirham', rate: 3.67, symbol: 'د.إ' },
    { code: 'AFN', name: 'Afghan Afghani', rate: 70.79, symbol: '؋' },
    { code: 'ALL', name: 'Albanian Lek', rate: 93.7, symbol: 'L' },
    { code: 'AMD', name: 'Armenian Dram', rate: 388.06, symbol: '֏' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', rate: 1.79, symbol: 'ƒ' },
    { code: 'AOA', name: 'Angolan Kwanza', rate: 865.03, symbol: 'Kz' },
    { code: 'ARS', name: 'Argentine Peso', rate: 911.67, symbol: '$' },
    { code: 'AUD', name: 'Australian Dollar', rate: 1.5, symbol: 'A$' },
    { code: 'AWG', name: 'Aruban Florin', rate: 1.79, symbol: 'ƒ' },
    { code: 'AZN', name: 'Azerbaijani Manat', rate: 1.7, symbol: '₼' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', rate: 1.83, symbol: 'KM' },
    { code: 'BBD', name: 'Barbadian Dollar', rate: 2, symbol: 'Bds$' },
    { code: 'BDT', name: 'Bangladeshi Taka', rate: 117.49, symbol: '৳' },
    { code: 'BGN', name: 'Bulgarian Lev', rate: 1.83, symbol: 'лв' },
    { code: 'BHD', name: 'Bahraini Dinar', rate: 0.376, symbol: '.د.ب' },
    { code: 'BIF', name: 'Burundian Franc', rate: 2865.62, symbol: 'FBu' },
    { code: 'BMD', name: 'Bermudian Dollar', rate: 1, symbol: '$' },
    { code: 'BND', name: 'Brunei Dollar', rate: 1.36, symbol: 'B$' },
    { code: 'BOB', name: 'Bolivian Boliviano', rate: 6.92, symbol: 'Bs.' },
    { code: 'BRL', name: 'Brazilian Real', rate: 5.52, symbol: 'R$' },
    { code: 'BSD', name: 'Bahamian Dollar', rate: 1, symbol: 'B$' },
    { code: 'BTN', name: 'Bhutanese Ngultrum', rate: 83.47, symbol: 'Nu.' },
    { code: 'BWP', name: 'Botswana Pula', rate: 13.63, symbol: 'P' },
    { code: 'BYN', name: 'Belarusian Ruble', rate: 3.28, symbol: 'Br' },
    { code: 'BZD', name: 'Belize Dollar', rate: 2, symbol: 'BZ$' },
    { code: 'CAD', name: 'Canadian Dollar', rate: 1.37, symbol: 'C$' },
    { code: 'CDF', name: 'Congolese Franc', rate: 2826.99, symbol: 'FC' },
    { code: 'CHF', name: 'Swiss Franc', rate: 0.898, symbol: 'CHF' },
    { code: 'CLP', name: 'Chilean Peso', rate: 950.99, symbol: '$' },
    { code: 'CNY', name: 'Chinese Yuan Renminbi', rate: 7.28, symbol: '¥' },
    { code: 'COP', name: 'Colombian Peso', rate: 4129.85, symbol: '$' },
    { code: 'CRC', name: 'Costa Rican Colon', rate: 522.5, symbol: '₡' },
    { code: 'CUP', name: 'Cuban Peso', rate: 24, symbol: '$' },
    { code: 'CVE', name: 'Cape Verdean Escudo', rate: 103.02, symbol: '$' },
    { code: 'CZK', name: 'Czech Koruna', rate: 23.37, symbol: 'Kč' },
    { code: 'DJF', name: 'Djiboutian Franc', rate: 177.72, symbol: 'Fdj' },
    { code: 'DKK', name: 'Danish Krone', rate: 6.97, symbol: 'kr' },
    { code: 'DOP', name: 'Dominican Peso', rate: 59.02, symbol: 'RD$' },
    { code: 'DZD', name: 'Algerian Dinar', rate: 134.69, symbol: 'د.ج' },
    { code: 'EGP', name: 'Egyptian Pound', rate: 48.03, symbol: '£' },
    { code: 'ERN', name: 'Eritrean Nakfa', rate: 15, symbol: 'Nfk' },
    { code: 'ETB', name: 'Ethiopian Birr', rate: 57.74, symbol: 'Br' },
    { code: 'FJD', name: 'Fijian Dollar', rate: 2.23, symbol: 'FJ$' },
    { code: 'FKP', name: 'Falkland Islands Pound', rate: 0.791, symbol: '£' },
    { code: 'FOK', name: 'Faroese Krona', rate: 6.97, symbol: 'kr' },
    { code: 'GBP', name: 'British Pound', rate: 0.791, symbol: '£' },
    { code: 'GEL', name: 'Georgian Lari', rate: 2.83, symbol: '₾' },
    { code: 'GGP', name: 'Guernsey Pound', rate: 0.791, symbol: '£' },
    { code: 'GHS', name: 'Ghanaian Cedi', rate: 15.28, symbol: '₵' },
    { code: 'GIP', name: 'Gibraltar Pound', rate: 0.791, symbol: '£' },
    { code: 'GMD', name: 'Gambian Dalasi', rate: 66.24, symbol: 'D' },
    { code: 'GNF', name: 'Guinean Franc', rate: 8576.05, symbol: 'FG' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', rate: 7.76, symbol: 'Q' },
    { code: 'GYD', name: 'Guyanese Dollar', rate: 209.01, symbol: 'G$' },
    { code: 'HKD', name: 'Hong Kong Dollar', rate: 7.81, symbol: 'HK$' },
    { code: 'HNL', name: 'Honduran Lempira', rate: 24.73, symbol: 'L' },
    { code: 'HRK', name: 'Croatian Kuna', rate: 7.04, symbol: 'kn' },
    { code: 'HTG', name: 'Haitian Gourde', rate: 132.37, symbol: 'G' },
    { code: 'HUF', name: 'Hungarian Forint', rate: 370.43, symbol: 'Ft' },
    { code: 'IDR', name: 'Indonesian Rupiah', rate: 16412.74, symbol: 'Rp' },
    { code: 'ILS', name: 'Israeli New Shekel', rate: 3.76, symbol: '₪' },
    { code: 'IMP', name: 'Isle of Man Pound', rate: 0.791, symbol: '£' },
    { code: 'INR', name: 'Indian Rupee', rate: 83.47, symbol: '₹' },
    { code: 'IQD', name: 'Iraqi Dinar', rate: 1309.37, symbol: 'ع.د' },
    { code: 'IRR', name: 'Iranian Rial', rate: 42051.19, symbol: '﷼' },
    { code: 'ISK', name: 'Icelandic Krona', rate: 139.18, symbol: 'kr' },
    { code: 'JEP', name: 'Jersey Pound', rate: 0.791, symbol: '£' },
    { code: 'JMD', name: 'Jamaican Dollar', rate: 153.52, symbol: 'J$' },
    { code: 'JOD', name: 'Jordanian Dinar', rate: 0.709, symbol: 'د.ا' },
    { code: 'JPY', name: 'Japanese Yen', rate: 143.72, symbol: '¥' },
    { code: 'KES', name: 'Kenyan Shilling', rate: 141.79, symbol: 'KSh' },
    { code: 'KGS', name: 'Kyrgyzstani Som', rate: 87.93, symbol: 'с' },
    { code: 'KHR', name: 'Cambodian Riel', rate: 4124.99, symbol: '៛' },
    { code: 'KID', name: 'Kiribati Dollar', rate: 1.5, symbol: 'A$' },
    { code: 'KMF', name: 'Comorian Franc', rate: 462.16, symbol: 'CF' },
    { code: 'KRW', name: 'South Korean Won', rate: 1305.12, symbol: '₩' },
    { code: 'KWD', name: 'Kuwaiti Dinar', rate: 0.307, symbol: 'د.ك' },
    { code: 'KYD', name: 'Cayman Islands Dollar', rate: 0.833, symbol: 'CI$' },
    { code: 'KZT', name: 'Kazakhstani Tenge', rate: 454.18, symbol: '₸' },
    { code: 'LAK', name: 'Lao Kip', rate: 18688.36, symbol: '₭' },
    { code: 'LBP', name: 'Lebanese Pound', rate: 15000, symbol: 'ل.ل' },
    { code: 'LKR', name: 'Sri Lankan Rupee', rate: 311.96, symbol: 'Rs' },
    { code: 'LRD', name: 'Liberian Dollar', rate: 184.21, symbol: 'L$' },
    { code: 'LSL', name: 'Lesotho Loti', rate: 19.08, symbol: 'L' },
    { code: 'LYD', name: 'Libyan Dinar', rate: 4.76, symbol: 'ل.د' },
    { code: 'MAD', name: 'Moroccan Dirham', rate: 9.77, symbol: 'د.م.' },
    { code: 'MDL', name: 'Moldovan Leu', rate: 17.96, symbol: 'L' },
    { code: 'MGA', name: 'Malagasy Ariary', rate: 4484.14, symbol: 'Ar' },
    { code: 'MKD', name: 'Macedonian Denar', rate: 57.48, symbol: 'ден' },
    { code: 'MMK', name: 'Burmese Kyat', rate: 2104.14, symbol: 'K' },
    { code: 'MNT', name: 'Mongolian Tughrik', rate: 3447.27, symbol: '₮' },
    { code: 'MOP', name: 'Macanese Pataca', rate: 8.04, symbol: 'MOP$' },
    { code: 'MRU', name: 'Mauritanian Ouguiya', rate: 37.67, symbol: 'UM' },
    { code: 'MUR', name: 'Mauritian Rupee', rate: 44.93, symbol: '₨' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', rate: 15.39, symbol: 'Rf' },
    { code: 'MWK', name: 'Malawian Kwacha', rate: 1078.66, symbol: 'MK' },
    { code: 'MXN', name: 'Mexican Peso', rate: 17.13, symbol: '$' },
    { code: 'MYR', name: 'Malaysian Ringgit', rate: 4.69, symbol: 'RM' },
    { code: 'MZN', name: 'Mozambican Metical', rate: 63.98, symbol: 'MT' },
    { code: 'NAD', name: 'Namibian Dollar', rate: 19.08, symbol: 'N$' },
    { code: 'NGN', name: 'Nigerian Naira', rate: 779.77, symbol: '₦' },
    { code: 'NIO', name: 'Nicaraguan Cordoba', rate: 36.45, symbol: 'C$' },
    { code: 'NOK', name: 'Norwegian Krone', rate: 10.46, symbol: 'kr' },
    { code: 'NPR', name: 'Nepalese Rupee', rate: 133.53, symbol: 'रू' },
    { code: 'NZD', name: 'New Zealand Dollar', rate: 1.64, symbol: 'NZ$' },
    { code: 'OMR', name: 'Omani Rial', rate: 0.384, symbol: 'ر.ع.' },
    { code: 'PAB', name: 'Panamanian Balboa', rate: 1, symbol: 'B/.' },
    { code: 'PEN', name: 'Peruvian Sol', rate: 3.68, symbol: 'S/' },
    { code: 'PGK', name: 'Papua New Guinean Kina', rate: 3.63, symbol: 'K' },
    { code: 'PHP', name: 'Philippine Peso', rate: 55.38, symbol: '₱' },
    { code: 'PKR', name: 'Pakistani Rupee', rate: 286.88, symbol: '₨' },
    { code: 'PLN', name: 'Polish Zloty', rate: 4.15, symbol: 'zł' },
    { code: 'PYG', name: 'Paraguayan Guarani', rate: 7284.62, symbol: '₲' },
    { code: 'QAR', name: 'Qatari Riyal', rate: 3.64, symbol: 'ر.ق' },
    { code: 'RON', name: 'Romanian Leu', rate: 4.64, symbol: 'lei' },
    { code: 'RSD', name: 'Serbian Dinar', rate: 109.33, symbol: 'дин.' },
    { code: 'RUB', name: 'Russian Ruble', rate: 87.59, symbol: '₽' },
    { code: 'RWF', name: 'Rwandan Franc', rate: 1195.66, symbol: 'FRw' },
    { code: 'SAR', name: 'Saudi Riyal', rate: 3.75, symbol: 'ر.س' },
    { code: 'SBD', name: 'Solomon Islands Dollar', rate: 8.42, symbol: 'SI$' },
    { code: 'SCR', name: 'Seychellois Rupee', rate: 12.97, symbol: '₨' },
    { code: 'SDG', name: 'Sudanese Pound', rate: 600, symbol: 'ج.س.' },
    { code: 'SEK', name: 'Swedish Krona', rate: 10.75, symbol: 'kr' },
    { code: 'SGD', name: 'Singapore Dollar', rate: 1.36, symbol: 'S$' },
    { code: 'SHP', name: 'Saint Helena Pound', rate: 0.791, symbol: '£' },
    { code: 'SLL', name: 'Sierra Leonean Leone', rate: 20758.98, symbol: 'Le' },
    { code: 'SOS', name: 'Somali Shilling', rate: 568.5, symbol: 'Sh' },
    { code: 'SRD', name: 'Surinamese Dollar', rate: 38.02, symbol: '$' },
    { code: 'SSP', name: 'South Sudanese Pound', rate: 984.86, symbol: '£' },
    { code: 'STN', name: 'São Tomé and Príncipe Dobra', rate: 23.67, symbol: 'Db' },
    { code: 'SYP', name: 'Syrian Pound', rate: 12845, symbol: '£' },
    { code: 'SZL', name: 'Eswatini Lilangeni', rate: 19.08, symbol: 'E' },
    { code: 'THB', name: 'Thai Baht', rate: 35.22, symbol: '฿' },
    { code: 'TJS', name: 'Tajikistani Somoni', rate: 10.99, symbol: 'SM' },
    { code: 'TMT', name: 'Turkmenistan Manat', rate: 3.5, symbol: 'T' },
    { code: 'TND', name: 'Tunisian Dinar', rate: 3.05, symbol: 'د.ت' },
    { code: 'TOP', name: 'Tongan Paʻanga', rate: 2.37, symbol: 'T$' },
    { code: 'TRY', name: 'Turkish Lira', rate: 26.1, symbol: '₺' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', rate: 6.77, symbol: 'TT$' },
    { code: 'TVD', name: 'Tuvaluan Dollar', rate: 1.5, symbol: 'T$' },
    { code: 'TWD', name: 'New Taiwan Dollar', rate: 30.84, symbol: 'NT$' },
    { code: 'TZS', name: 'Tanzanian Shilling', rate: 2397.7, symbol: 'TSh' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', rate: 36.88, symbol: '₴' },
    { code: 'UGX', name: 'Ugandan Shilling', rate: 3753.75, symbol: 'USh' },
    { code: 'UYU', name: 'Uruguayan Peso', rate: 38.62, symbol: '$U' },
    { code: 'UZS', name: 'Uzbekistani Som', rate: 12042.87, symbol: 'soʻm' },
    { code: 'VES', name: 'Venezuelan Bolívar', rate: 26.07, symbol: 'Bs.S' },
    { code: 'VND', name: 'Vietnamese Dong', rate: 23500, symbol: '₫' },
    { code: 'VUV', name: 'Vanuatu Vatu', rate: 120.68, symbol: 'VT' },
    { code: 'WST', name: 'Samoan Tala', rate: 2.69, symbol: 'WS$' },
    { code: 'XAF', name: 'Central African CFA Franc', rate: 603.48, symbol: 'FCFA' },
    { code: 'XCD', name: 'East Caribbean Dollar', rate: 2.7, symbol: '$' },
    { code: 'XDR', name: 'Special Drawing Rights', rate: 0.74, symbol: 'SDR' },
    { code: 'XOF', name: 'West African CFA Franc', rate: 603.48, symbol: 'CFA' },
    { code: 'XPF', name: 'CFP Franc', rate: 111.7, symbol: '₣' },
    { code: 'YER', name: 'Yemeni Rial', rate: 250.5, symbol: '﷼' },
    { code: 'ZAR', name: 'South African Rand', rate: 19.08, symbol: 'R' },
    { code: 'ZMW', name: 'Zambian Kwacha', rate: 18.25, symbol: 'ZK' },
    { code: 'ZWL', name: 'Zimbabwean Dollar', rate: 631.08, symbol: 'Z$' },
  ];
  await Promise.all([
    prisma.currency.upsert({
      where: {
        id: 'b6ecaefd-510d-47cf-83a1-b96494496a84',
      },
      update: {},
      create: {
        id: 'b6ecaefd-510d-47cf-83a1-b96494496a84',
        code: 'USD',
        name: 'US Dollar',
        rate: 1,
        symbol: '$',
      },
    }),

    prisma.currency.upsert({
      where: {
        id: '4c9c5f3c-2a1b-4cf3-8d64-0e1e26f5b367',
      },
      update: {},
      create: {
        id: '4c9c5f3c-2a1b-4cf3-8d64-0e1e26f5b367',
        code: 'EUR',
        name: 'Euro',
        rate: 0.934,
        symbol: '€',
      },
    }),

    ...currencies.map((currency) =>
      prisma.currency.upsert({
        where: {
          code: currency.code,
        },
        update: {},
        create: {
          code: currency.code,
          name: currency.name,
          rate: currency.rate,
          symbol: currency.symbol,
        },
      }),
    ),
  ]);
}
